# Generated by Django 2.0.5 on 2018-05-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField(verbose_name='Date of birth')),
                ('angel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='angelsystem.User')),
            ],
        ),
    ]
